### ISSUE TITLE
Would be nice to seed all directories with a README

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Rainbow-Code#112]

**Comment by babu-thomas** [comment]
Are you looking for something like [this](https://github.com/babu-thomas/Rainbow-Code/tree/master/challenges/CC_01_StarField)?

I just copied the video description with some minor edits. If this is acceptable then I will send a pull request after adding README to the other challenge folders too.

**Comment by shiffman** [comment]
Yup that looks great! Any other ideas welcome.

**Comment by babu-thomas** [comment]
Okay! I will send a pull request.

**Comment by shiffman** [comment]
This is happening. . .
