### ISSUE TITLE
CC_65_Pong p5.js?

### ISSUE THREAD

**Issue by pleabargain** [CodingTrain/Rainbow-Code#126]
Hello, you mentioned in your vid that you would post the P5 js for pong as well.
https://youtu.be/IIrC5Qcb2G4

following up :)

thank you!
Dennis

**Comment by fcssb** [comment]
Yeah that would be cool! I second this 👍

**Comment by RedHenDev** [comment]
Here's an example in JavaScript, using p5: http://codepen.io/RedHenDev/pen/evLBYM

Feel free to update the ai and add keyboard input (in fact, I should add this in tonight...)

Let me know if any issues! Enjoy!

**Comment by RedHenDev** [comment]
OK -- arrow keys can control player 1 paddle now :)

**Comment by meiamsome** [comment]
Closing in favour of #267

**Comment by meiamsome** [comment]
Just a follow up, that this has just been more directly ported by @madacoo is now in the repository!
