### ISSUE TITLE
Github pages links in README

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Rainbow-Code#128]
This repo is now set to have github pages enabled. So might make sense for p5.js example to link in the README to the example running in the browser.

**Comment by yochem** [comment]
I am trying to make a [jekyll](jekyllrb.com)-injected github-page for this. It works well, but you have to include
```yaml
---
# title must be exactly the same as the folder name :) 
title: CC_17_SpaceColonizer_p5
---
```
In every html file. It's called [YAML front matter](https://jekyllrb.com/docs/frontmatter/) and helps Jekyll to recognize the html file like a page. This way it's possible to loop through all of the challenges. It's a little devious though. 

To create a list with all challenges, I used this (liquid) html:
```liquid
<ul>
  {% for cc in site.challenges %}
    <a href="challenges/{{ cc.title }}"><li>{{ cc.title }}</li></a>
  {% endfor %}
</ul>
```
Maybe Jekyll isn't the best solution, but it should work fine. After creating the webpage, just commit the challenge as usual and add the front matter in the html-file. 

I hope you like the idea! If so, I am happy to go on with coding the webpage for this repo 😄

**Comment by shiffman** [comment]
I definitely like this idea! I've wanted to try to implement something like this but just haven't had the time to look into it. I use jekyll for my other sites (shiffman.net, natureofcode.com, thecodingtrain.com) etc.

One thing I might suggest is to build it with little to no "design" point of view.  Very basic / barebones and then I can later think about styling it with a designer?

**Comment by yochem** [comment]
I'm going to work on it after the weekend! You'll see it next week I hope :)

**Comment by yochem** [comment]
Hey @shiffman, 
If you've used Jekyll you probably know by now it has a lot of files in the root directory. It can sometimes look like a mess and makes the source code for the vids harder to find. I was thinking about making another repository for the website, with a submodule of the Rainbow-Code repo (this one). However, I don't have a lot of experience with git submodules, but that's gonna be alright! Please let me know what you think what the best option is 😄

**Comment by shiffman** [comment]
Using a submodule is an interesting possibility! However, I have found that they can be tricky and confusing to work with and also can make it difficult for others to contribute to the project unless they understand submodules.

I don't mind having extra folders in the root folder, we could move all the code into its own directory. And also perhaps ultimately doing this would be a step towards users going to the actual website to find the code and tutorials rather than coming to the github repo?

The key for me would be starting with some very clean and simple. 

But really I'm open to any ideas!

**Comment by haideralipunjabi** [comment]
Can't we have a separate branch for Github Pages?

**Comment by shiffman** [comment]
This is all new with #347 and more going forward!
