### ISSUE TITLE
Starcraft Bot [SSCAIT] Student StarCraft AI Tournament 2017 

### ISSUE THREAD

**Issue by DamianReloaded** [CodingTrain/Rainbow-Code#129]
There is a JAVA binding for it. And it seems pretty straightforward.
This could be cool to demonstrate some machine lerning algorithms.
See:
http://sscaitournament.com/index.php?action=downloads

**Comment by meiamsome** [comment]
Hello, this repository is for the code from tutorials only, please but all topic suggestions/requests in https://github.com/CodingTrain/Rainbow-Topics thanks.
