### ISSUE TITLE
CC_02_MengerSponge_p5.js space between new boxes

### ISSUE THREAD

**Issue by dpipkin** [CodingTrain/Rainbow-Code#138]
I'm not exactly sure how p5.js differs from Processing in how it draws boxes, but this is what happens when you click for new boxes:  
  
<img src="https://cloud.githubusercontent.com/assets/6591123/24914706/3e5231fe-1e92-11e7-86af-02251518ac13.gif" height=200 width=200>

**Comment by meiamsome** [comment]
This was partially fixed a while ago, but I just pushed a new update that renders the fix correctly.
