### ISSUE TITLE
Idea for a coding challenge: 3D Ray-casting

### ISSUE THREAD

**Issue by The-Code-Beetle** [CodingTrain/Rainbow-Code#140]
3D Ray-casting is a simple method  to create a 3D world.
The coding challenge can be in either p5 or Processing.
Links related to the topic:
[Article about 3D Ray-Casting with a version in C++](http://lodev.org/cgtutor/raycasting.html)
[Example in Javascript / ProcessingJS](https://www.khanacademy.org/computer-programming/jack-raycaster-new-fake-3d/1163555850)

**Comment by meiamsome** [comment]
Hello, please vote for coding challenged in the Rainbow Topics Repo. A search for Ray Casting is here: https://github.com/CodingTrain/Rainbow-Topics/issues?q=is%3Aissue%20is%3Aopen%20ray%20casting
