### ISSUE TITLE
Coding Challenge: Langton's Ant

### ISSUE THREAD

**Issue by Naahuel** [CodingTrain/Rainbow-Code#141]
https://youtu.be/NWBToaXK5T0

This should be easy! And entertaining :)

**Comment by pranavgade20** [comment]
Here is my go at it : https://codepen.io/anon/pen/EmpqjG
Not exactly The most beautiful piece of art, but you are free to make it better.
PS:You may want to zoom in to see it better.

Thanks.

Here is the code:
`var text;
function setup(){
	createCanvas(500, 500);
	background(200);

   text = createP('0');
}

var x = 250;
var y = 250;
var ant_face = 0;
var n = 0;

function draw(){
	loadPixels();

	var i = (x + (y * width))*4;
   var avg = (pixels[i+0]+pixels[i+1]+pixels[i+2])/3;

   if(avg<125){//pixel is black
      ant_face+=3;//turn right 3 times=(left once)
      ant_face%=4;

      pixels[i+0] = 255;
      pixels[i+1] = 255;
      pixels[i+2] = 255;
	   // pixels[i+3] = 255;
   }else{
      ant_face+=1;//turn right once
      ant_face%=4;

      pixels[i+0] = 0;
      pixels[i+1] = 0;
      pixels[i+2] = 0;
   }

   updatePixels();

   if(ant_face == 0){//facing top
      y--;
   }else if(ant_face == 1){//facing right
      x++;
   }else if(ant_face == 2){//facing down
      y++;;
   }else{//facing left
      x--;
   }
   n++;
   text.html(n);
}`

**Comment by Naahuel** [comment]
Looks like it works pretty good! But yeah it needs to be bigger haha. Thanks!

**Comment by pranavgade20** [comment]
To make it bigger, maybe you can tweak the pixelWidth() ?
Coz storing the elements in an array will require a lot of memory and slow it down a lot.

**Comment by rhdunn** [comment]
Some things I have experimented with in the past when playing with my own implementation:

1.  Wrap the world space (so if the ant moves off to the left, move it over to the right edge) -- this allows the ant to interact with the hives (central blob) and highways (diagonal moving pattern).

2.  Try 2 ants in different positions -- there are 3 different behaviours: hive/highway; create/destroy blob; expand/collapse diamond.

3.  Support different actions on a colour (turn left; turn right; turn 180; don't turn), with multiple colours (e.g. a 3 colour cycle).

Additionally, this could be extended to run more general turmites (https://en.wikipedia.org/wiki/Turmite).

**Comment by meiamsome** [comment]
Hello, please vote here to see a video made: https://github.com/CodingTrain/Rainbow-Topics/issues/18
