### ISSUE TITLE
Version of the TSP with genetic

### ISSUE THREAD

**Issue by acaunce** [CodingTrain/Rainbow-Code#145]
I created this after your last set of travelling salesman problem videos to see if I could get the GA working.

The crossover is pretty crazy I think (coding at 2am is never a good idea) but it somewhat works and it has the brute force version running at the same time so you can see the speed. It runs the the same number of iterations of the brute force every frame as the population size so its a fair(_ish_) test. For more than about 9 cities the brute force takes a really _REALLY_ long time!!!

Thought it might be interesting...

https://github.com/acaunce/my-crappy-sketches/tree/master/travelling_salesman

Was going to PR the readme but its not up yet and if I wait Ill forget :p

**Comment by meiamsome** [comment]
Hey there, @acaunce - would you like to PR the README for me now?

**Comment by shiffman** [comment]
Yes, please pull request to the README!
