### ISSUE TITLE
In 7.13.3 and 7.13.4 folder, images won't load from data folder

### ISSUE THREAD

**Issue by EmbraceLife** [CodingTrain/Rainbow-Code#15]
Hi Dan, 

both folders work fine at the moment. But l want images to be stored in the folder called data, so I created a fold named data, and put the image file into it. However, the image won't load. Images are loaded fine outside of data folder.

What did I do wrong?

Thanks

**Comment by shiffman** [comment]
Did you say `loadImage('data/filename.jpg')`?  Unlike Processing, p5 won't look in the data folder automatically.

**Comment by EmbraceLife** [comment]
yes, I see, thanks.
