### ISSUE TITLE
Coding Challenge: Handwriting Recognition

### ISSUE THREAD

**Issue by RiPs7** [CodingTrain/Rainbow-Code#159]
In the context of Intelligence and Learning, maybe you could build an app for the user to draw a letter (or ideally a whole word) with their mouse and then the app would recognize based on a dataset (maybe using k-nearest neighbors algorithm), the letter(s) they have drawn.

**Comment by Svartur** [comment]
idk if Processing is powerful enough

**Comment by RiPs7** [comment]
I dont think it has anything to do with how much powerful a tool is.. Implementing a simple handwriting recognition app (which at least recognizes a single letter) can be done relatively easily and it will make use of some really useful algorithms e.g. k-nearest neighbors.

**Comment by Svartur** [comment]
So why is Google translator unable to recognize handwritten text in offline mode? I know, they want to collect data to improve their recognition but it can be done as soon as user connects to the internet later. I mean making database and data structures for processing would be not as easy

**Comment by RiPs7** [comment]
wow, I am talking about something simple, for recognizing just a single character, for example a capital A over a capital B and nothing more.. and you are comparing this idea to a translating app made by Google?? what's the point in that? I did not even mention anything about collecting user data.. just a simple json with collection of points representing the possible characters on a canvas might be enough for demonstrating a k-nn algorithm. also it might be a good application for the concept of the pearson correlation score, that Dan mentioned in the nearest neighbors recommendation engine coding challenge.. also, this app could have just a basic implementation to recognize characters for only one user, where the handwriting is specific to this user.

**Comment by MavastDev** [comment]
Great idea @RiPs7 !

**Comment by thisdotmatt** [comment]
Yeah I think it would be a great idea, but Svartur does have a point though it would be a challenge.  However, that's what coding is all about, right? I guess for the code to work, the drawing part would be easy, but the problem is noticing every line that the user draws and interpreting that.  I would suggest to Dan that if he does this he should make the drawing so that the "drawing" is really a group of tiny lines.  And I also think it would be a great lesson in Machine Learning.

**Comment by RiPs7** [comment]
Well, in a silly implementation of mine some time ago, I kinda had two sub-apps. Both of them had a canvas for letting me draw a letter on it, but the first one was for uploading it to a dataset, as a set of points in a .json file and the other was for recognizing the drawing based on the preloaded file. So, for example, if a user drew the letter A, uploaded it and they repeated the process again and again, the dataset would either include all the points from each time, or an aggregation of them. Maybe that is the core idea but I'd love to see Dan implement a much more consistent app. :)

**Comment by meiamsome** [comment]
Hello, this repository is for the code from tutorials only, please but all topic suggestions/requests in https://github.com/CodingTrain/Rainbow-Topics thanks.
