### ISSUE TITLE
Coding Challenge: Dragon Curve

### ISSUE THREAD

**Issue by broodjetom** [CodingTrain/Rainbow-Code#162]
How about a "simple" coding challenge about the dragon curve?
[https://en.wikipedia.org/wiki/Dragon_curve](https://en.wikipedia.org/wiki/Dragon_curve)

**Comment by meiamsome** [comment]
Hello, please see the discussion here: https://github.com/CodingTrain/Rainbow-Topics/issues/466. Feel free to vote there to have a video created.
