### ISSUE TITLE
Does not the pickOne() function require a sorted list to operate properly?

### ISSUE THREAD

**Issue by akseidel** [CodingTrain/Rainbow-Code#165]
It seems to me the pickOne() function, for example used in the TSP, requires the list it operates on to be sorted by the probability value in order to function properly. There have been a few variations to the pickOne() as used in the TSP.  At one time it was similar to this where it is supposed to favor selecting population members having a larger normalized fitness value. 

`function pickOne() {
  var index = -1;
  var r = random(1);
  while (r > 0) {
    index += 1;
    r -= population[index].fitness;
  }
  return population[index];
}`

Consider a simplified population having members 0|A|.10, 1|B|.60, 2|C|.20 and 3|D|.10 where there are four members indexed 0 to 3, named A,B,C & D, having fitness numbers .10, .60, .20 and .10 in that order. The above pickOne function would select member A when r=.10 or less and it would select member B for all other values of r.  The function does work as advertised when the members are sorted by increasing fitness value 0|A|.10, 1|D|.10, 2|C|.20 and 3|B|.60.

Sorting the population object array on fitness prior to using the pickOne() fixes the situation. The following would do this.

`// sort the population based upon the normalized fitness
  population.sort(function(a, b) {
    return a.fitness - b.fitness;
  });`

At some point in time the NOC-S17-2 03_TSP_GA_CROSSOVER code was radically changed to separate the population from the population's fitness. The fix may not be so simple.

**Comment by meiamsome** [comment]
I believe this works correctly. A run through of your example with `r = - 0.99` would be:
```
loop 0:
index = 0
r = r - 0.1 // 0.89
loop 1:
index = 1
r = r - 0.6 // 0.29
loop 2:
index = 2
r = r - 0.2 // 0.9
loop 3:
index = 3
r = r - 0.1 // -0.1
Loop terminates, D returned
```

Let me know if that reasoning doesn't seem sound to you.

**Comment by akseidel** [comment]
r starts out at random(1). It would be positive only. The loop drops out when r goes negative. Starting with .99 should select the highest member, but it selects D which is .10. Sorting first results in .60 being selected. B is not selected for all values larger than .10 as I had stated. B is selected for all values between A and A+B. C is selected for all values between B and A+B+C and so on. That is why the normalized value list needs to be sorted first.

**Comment by meiamsome** [comment]
Ah, I think I see where the misunderstanding is - the `pickOne` is built to pick from the array with a given probability (.1 for A, .6 for B etc.) - so it assigns ranges in the region [0, 1) to each of the values relative to the size. So, A has [0, .1), B has [.1, .7), C has [.7, .9) and D has [.9, 1). The important thing to notice is that the probability of picking any element is based on how wide it's range is, and not at all related to where it is along the total range. [0, .6) has the same probability of being picked as [.3, 1) - despite being placed differently.

**Comment by shiffman** [comment]
@meiamsome's explanation makes sense to me.
