### ISSUE TITLE
Coding Challenge: Plotting electron occurrence probability of a hydrogen atom using the hydrogen quantum wave function.

### ISSUE THREAD

**Issue by Demonstrandum** [CodingTrain/Rainbow-Code#178]
Create a hydrogen's electron density plot at different energies, using the hydrogen wave function.

Resources:
https://en.wikipedia.org/wiki/Hydrogen_atom#Schr.C3.B6dinger_equation
https://en.wikipedia.org/wiki/Wave_function
http://hyperphysics.phy-astr.gsu.edu/hbase/quantum/hydwf.html           

![hydrogen-wave-func](https://wikimedia.org/api/rest_v1/media/math/render/svg/e9f5c43f270a7e4c6aa8fab980ec3a1a13f1ff11)
Like so, where a brighter colour means a greater likelihood of finding an electron there:
![hydrogen_density_plots-1](https://user-images.githubusercontent.com/26842759/27139150-20d945d0-511a-11e7-98fa-9d043c112d9a.png)

**Comment by meiamsome** [comment]
Hello, this repository is for the code from tutorials only, please but all topic suggestions/requests in https://github.com/CodingTrain/Rainbow-Topics thanks.

**Comment by Demonstrandum** [comment]
Thanks
