### ISSUE TITLE
Coding Challenge: Snake VS Block

### ISSUE THREAD

**Issue by Elfocrash** [CodingTrain/Rainbow-Code#181]
As the game has been blowing up recently, it would be a great change to do a coding challenge in Snake VS Block.

Basically an endless runner where the main goal is to last as long as possible by collecting balls that increase you length and then using this length to smash through blocks.

Google play link reference: https://play.google.com/store/apps/details?id=com.bentostudio.ballsvsblocks&hl=en

**Comment by RoseCrime** [comment]
Since here's already 2 likes I'll add youtube video link just in case : [](
https://www.youtube.com/watch?v=-3DDs1hjxZM)

**Comment by meiamsome** [comment]
Hello, this repository is for the code from tutorials only, please but all topic suggestions/requests in https://github.com/CodingTrain/Rainbow-Topics thanks.
