### ISSUE TITLE
Unnecessary verification on Minesweeper code (cell.js)

### ISSUE THREAD

**Issue by rhrlima** [CodingTrain/Rainbow-Code#184]
Just a small detail that does not provoke any bug or something the way it is right now.

The condition for the floodfill to be executed is only for cells with 0 bombs as neighbors. 
In cell.js line 85, we have:
```javascript
if (!neighbor.bee && !neighbor.revealed) {
    neighbor.reveal();
}
```
but the verification for "bee" is not necessary since, ALL neighbors of a 0 count cell are not bees for sure.

**Comment by meiamsome** [comment]
Good point, I added a comment and removed the check.
