### ISSUE TITLE
Snake VS Block

### ISSUE THREAD

**Issue by slowizzm** [CodingTrain/Rainbow-Code#185]
Coding Train Challenge?

Snake VS Block by Voodoo
https://appsto.re/us/N2vIjb.i

**Comment by JosefKuchar** [comment]
Maybe with NN

**Comment by Elfocrash** [comment]
I already proposed that here: https://github.com/CodingTrain/Rainbow-Code/issues/181

**Comment by slowizzm** [comment]
@Elfocrash ... my bad. I didn't see it your proposal.
