### ISSUE TITLE
Ballz (Game)

### ISSUE THREAD

**Issue by thisdotmatt** [CodingTrain/Rainbow-Code#187]
I heard about this game, and I thought it would be a fun coding challenge in p5.js.  Check it out!
Every block has a fixed number that moves with it, and when a certain number of balls hits it, it disappears.
Try playing it and you will see the game concept.

https://play.google.com/store/apps/details?id=com.ketchapp.ballz&hl=en

**Comment by JosefKuchar** [comment]
This is only clone of [BBTan](https://play.google.com/store/apps/details?id=com.crater.bbtan&hl=cs)

**Comment by thisdotmatt** [comment]
I mainly am interested in seeing the concept being coded, not necessarily the specific game.

**Comment by RoseCrime** [comment]
Pretty simple one ,guess all concepts of this game already was mentioned in other tutorials and challenges.
Block with fixed number that moves with it : 
All blocks should be objects - rectangles with x,y values. (positions)
They moves ? Okay, so make move() method for each block that will increase or decrease x/y as you need to.
Text stays on block? Allright, take block's x and y and apply them to text coordinates. (rectMode and textAlign should be CENTERed).
Ball need to hit block some amount of times - make object have health and reduce it each time ball hit (intersects  with) block.
Block's health<= 0? Allright,remove it.

Guess I can make this concept for you if you want too.

**Comment by typio** [comment]
I thought BBTan and Ballz are clones of [One More Brick] (https://play.google.com/store/apps/details?id=com.riftergames.onemorebrick)

**Comment by meiamsome** [comment]
Hello, this repository is for the code from tutorials only, please but all topic suggestions/requests in https://github.com/CodingTrain/Rainbow-Topics thanks.
