### ISSUE TITLE
Q&A #1 Side Scroller Game code

### ISSUE THREAD

**Issue by thisdotmatt** [CodingTrain/Rainbow-Code#188]
Hi I've been watching of few of the coding train issues and I then I came across this video:
https://www.youtube.com/watch?v=Ouza_4SsbLc
I have been doing game coding for a couple of months, so I'm relatively new to this.  I'm in the middle of making a side-scroller game, and I need the code for the gravity and what-not.  I've searched but I can't find the source code for this.  Can you please post it or point me to where it is?  Thanks so much.

**Comment by thisdotmatt** [comment]
Never mind I got what I needed.

**Comment by Chiggy-Playz** [comment]
@thisdotmatt where did you find the source code?
