### ISSUE TITLE
Reaction Diffusion rendering speed

### ISSUE THREAD

**Issue by paulmason** [CodingTrain/Rainbow-Code#192]
Hey Daniel!

Love all your work, you been inspiring me to get more creative with my coding. I was thinking of making some sort of interactive 2 player game with your reaction diffusion code. Where each player would take turns at adding a blob of ink, who's ever color consumes the canvas first wins. Kind of like Reversi https://en.wikipedia.org/wiki/Reversi

I noticed though that you set the canvas to 100x100px and its not very quick at rendering.  Do you know if there's a way I could speed up the rendering and still use Javascript? Also curious why Processing is faster than p5js? Thanks :)

p.s. Hope the recovery is going well!

**Comment by shiffman** [comment]
Pixel stuff is just very slow in JS. Maybe shaders and WEBGL would speed it up? For more, you can ask at http://forum.processing.org.
