### ISSUE TITLE
Coding Challenge : Sudoku

### ISSUE THREAD

**Issue by jperchoc** [CodingTrain/Rainbow-Code#193]
How about creating a Sudoku game ? There is a lot of fun things to do :
- checking if a grid is valid
- highlight errors (same number on row/line/square)
- show possible numbers in each cell
- generate a random grid
- create a solver

I have implemented most of those in [my version](https://github.com/jperchoc/sudoku) ([live version](http://plnkr.co/edit/XX1lZI?p=info)) and it was harder than I expected

**Comment by meiamsome** [comment]
Hello, Please vote in the Rainbow  Topics repository.

Relevant issues:
Generator: https://github.com/CodingTrain/Rainbow-Topics/issues/531
Solver: https://github.com/CodingTrain/Rainbow-Topics/issues/172
