### ISSUE TITLE
Animatiom effect in P5.js

### ISSUE THREAD

**Issue by lokeshchoudhary** [CodingTrain/Rainbow-Code#195]
# **i have been watch your series of tutorial on p5.js. And i had a question:-
i just want to know that , is there any way to make ellipse move on a particular path .
For example a ellipse is moving on a rectangular path.
please make a video.**

**Comment by Pauel-Rafau** [comment]
you should find everything [here](https://stackoverflow.com/questions/17083580/i-want-to-do-animation-of-an-object-along-a-particular-path)...

**Comment by meiamsome** [comment]
Hello, this repository is for the code from tutorials only, please but all topic suggestions/requests in https://github.com/CodingTrain/Rainbow-Topics thanks.

Also, see the above post it's pretty good.
