### ISSUE TITLE
Minesweeper/Beesweeper

### ISSUE THREAD

**Issue by LankySmurph** [CodingTrain/Rainbow-Code#199]
I have had the issue of when I implement your code into a webpage it tries to save the canvas as a canvas.png file every time I click on a square. Why would it do this?

Thank you for any attention you may give my question,

LankySmurph

**Comment by HaydenJolly** [comment]
https://github.com/CodingTrain/Rainbow-Code/blob/791870b687e3112a22ea12e9fda1a3fd8465e338/CodingChallenges/CC_71_minesweeper/sketch.js#L70-L84


This is probably happening because of line 83, which you can just remove.

**Comment by meiamsome** [comment]
Weird. I think this was added by accident. Fixed it now, thanks.
