### ISSUE TITLE
Coding challenge #57: Map doesn't scale properly when you change clat and clon

### ISSUE THREAD

**Issue by eJohnstonePhd1991** [CodingTrain/Rainbow-Code#204]
I tried this example myself and it works fine when clat and clon are set to 0,0, but when I set clat to 50, the points I draw move relative to the new center. I'm guessing this is because you are drawing the coordinates as if the center of the map corresponds to latitude = 0 and longitude = 0, which is no longer the case when you change these values.

**Comment by meiamsome** [comment]
Okay, I think I have fixed this now? Let me know if not!

**Comment by shiffman** [comment]
Awesome, thank you!
