### ISSUE TITLE
Genetic Algorithm Implemented in C#

### ISSUE THREAD

**Issue by YuryENG** [CodingTrain/Rainbow-Code#207]
Hi Rainbow codder. 
Thank you for the great work you put out there. 
I was inspired by your work and I would like to share with the community implementation of your algorithm in C#. 

I already have the code and a wiki article on my page and I will gladly provide this to you if you need it. 

Thank you for the great job you are doing and making this world a better place by educating millions of people.

**Comment by kleinesfilmroellchen** [comment]
Maybe you could make this a pull request not an issue?

**Comment by meiamsome** [comment]
Hello, please see the CONTRIBUTING file for how to do this - usually it's just to PR your info into the relevant README.
