### ISSUE TITLE
Different framerates for different functions inside draw function (question)

### ISSUE THREAD

**Issue by RoseCrime** [CodingTrain/Rainbow-Code#224]
So...let's imagine just for fast simple example.

We have 2 functions inside draw functions:

Income - increase player's money.
game - whole game function.

I want to run game() with max frameRate I can.
I also want Income() to run like once in 5s.

```
function draw () {
  game();
  income();
} 
```

Here's few problems:
a)I can use setInterval,but I don't want player to gain money while tab isn't active.
b)frameRate too low on some kind of phones - player gain money too fast while game is going slow.

So...Guess right direction is - dependence between frame rate and income rate.

And...I have 2 ideas right now : 

1.I can reduce gold and re-calculate everythin' to let it add gold per frame. 
But it's not the way I want it to work.

2.Guess I can use frameCount () ;
And just divide it by some number to get income rate I need...

_**But maybe here exist some other more simple way and I just don't see it?**_

**Comment by Merijn-DH** [comment]
So you want income() to be triggered every so often without losing the proportion between game() and income() when using slower devices or while ran in a different tab? Personally, I would just use
```
function draw() {
   game();
   if (frameCount() % 150 == 0)
      income();
}
```
as you already described as idea 2. Is this not already an easy enough solution?

**Comment by RoseCrime** [comment]
Yep,your code made it much more simple, nice way to count same "seconds" , but depending on speed too:)

**Comment by RoseCrime** [comment]
Actually...even this one doesn't work perfectly :D 
It can sometimes miss triggering things or even trigger too often and I'll show why: 

let's call frameRate () - rate
and frameCount - count to be short.

**Misses:**

rate = 60
count = 59
Nothing triggered;

Rate 58
count 60
Nothing triggered;

Rate 59
count 61
Nothing triggered;

Rate 60
count 62 
Nothing triggered;

E.t.c

**Repeating:**

Rate 59
count 59
Trigger;

Rate 60
count 60
Trigger

E.t.c.


So,in this case I guess I need to completely remake condition.
Best solution I see right now - reduce count each rate();
And then if count-rate >=0 -> trigger and reset counter to 0;
Still not perfect,but seems workable.

And since we can't change frameCount - we need our own counter.
so...

```
let counter = 0;

function draw() {
    if (counter - frameRate() >= 0) {
        //triggerThings;
        counter = 0;
    }
    counter++;
}
```

**Comment by gvitalie** [comment]
# setFrameRate(val)

If I understood correctly, maybe this could be of help: https://p5js.org/reference/#/p5/frameRate
 
For example, the function call **frameRate(30)** will attempt to refresh 30 times a second.
This is the same as setFrameRate(val). 

P.S.: Calling **frameRate()** with arguments that are not of the type numbers or are non positive also returns current framerate.

**Comment by Merijn-DH** [comment]
@RoseCrime, you're absolutely right. I hadn't thought about that yet. Don't know if there is a more elegant solution but for now your solution works fine.

**Comment by RoseCrime** [comment]
@gvitalie I Know we can set FrameRate ,but that doesn't mean we will always get exactly number we set in here , as I got from just a bit of tests.

with frameRate(30);

frameRate returns always values until 30.9 (I hope that's higher) and below.So getting 29 is pretty common thing(even for my PC,on phones it may differ even more),which will be cause of same bug (unstable calls).

Also,my method isn't perfect too,cause in this case if we'll want to make more functions depending on time - we'll need counters for each one.

**Comment by gvitalie** [comment]
## @RoseCrime 
> ### `Cite:`  
> I want to run game() with max frameRate I can.
> I also want doComPort() to run like once in 5s.

_... If so, I think, game() could run at frameRate we have,   
and doComPort() calculate depending of time{start, pause, stop} only when draw() is running._

![](http://static.skaip.org/img/emoticons/180x180/f6fcff/think.gif)  
### Tobias thinking: 
[Tobias name meaning - http://behindthename.com](https://www.behindthename.com/name/tobiah)
> **when draw() running and get settled event time for doComPort function,   
> then run doComPort() function**


```javascript
function doComPort(){ - fbody- }
function doCountTime(period){ - fbody- }

function draw(){
    if(doCountTime(period)){
          doComPort();
    } else {
         nirvana();
    }
}
```

_where **doComPort()**  is **doincome()** function._  

**Bibliography:**

> ####  Nirvana - Come As You Are - YouTube
_Note: Clinking on image below will open a video on YouToBee:_  
[![](https://img.youtube.com/vi/vabnZ9-ex7o/0.jpg)](https://www.youtube.com/watch?v=vabnZ9-ex7o)

**Comment by Merijn-DH** [comment]
What about something like this
```
let previousRate = 30;

function draw() {
   game();
   if (frameCount() % 5*previousRate == 0)
      previousRate = frameRate;
      income();
}
```

This way it won't skip any calls to income() and it will try to keep up with the framerate the device currently has. Do you think the lag/error of using the previous framerate would be too significant?

**Comment by gvitalie** [comment]
@RoseCrime 

I did this experiment.
Live demo: https://gvitalie.github.io/demolution/lemma/

> moving mouse on X axis will change frameRate:
```javascript
function draw() {
        ...
	frameRate(map(mouseX, 0, width, 1, 60));
        ...
```

**Comment by RoseCrime** [comment]
@gvitalie yep,that's exactly what I mean, frameRate can jump a lot and be case of unstable calls.
Even on PC for me frameRate jumps from 14 to 30 fps :D 

So...since I didn't understood your method mine is still most stable :D even if mess up code a bit =(

**Comment by gvitalie** [comment]
Good morning, @RoseCrime 

Have fun too! :)  

Your issue inspired think about this: what if ...? Enough words, let's see! :1234: 

[Live Demo example - https://gvitalie.github.io/demolution/Muse/](https://gvitalie.github.io/demolution/Muse/)  

![](https://lh3.googleusercontent.com/JMS4VhHB37k3k3e0fe8hUKtBOvWD_T3b3hXi5A4noFuXIR4lKpbPVDlT1zOPWj0mbff8HDDEn6y9gInjLdGcvVTYd7ZYVsb9HcIgO7AXjmppht56qYO6NFJfgVLI6YHbdtD83LGYRzNU1vEFUYSsAXczWsSXNvdoocyUvfpFPs_40Tf6Q6PzC2y36d3yaE7pB_ovVZnPDZc15vKveNh6mCcqpYy921KNkA4EqjtFEwqQ7TRQc0i6wvu6HeoBNgFYeELe1kEJmIxO4R03jyr4Gj1owQ6Lvo6yAM4oQRwi1bucX2sBSkWM5vXIZ9EqwsgBgD-Lr6qZdErmgk4dAN_3pjWHwB8eZVOiS8zyNioGn-k2ev6ecbx04EHoSwuUYrHHQ6v6HIhN5blrknUqCs5Gs_kJYMd-f4e9zs674_rOWcng5KXfEZQWNOuY1qb4ilWHK0gVu8a5s_zu8JD1maQHjoQFV4w4u_PZYd9acq8J5vvCTZugJAemZEFSzBNk5aJicfeXC4mjW-dJnN7NzWci58ICD1YoqiCbOEpor4009T82PKGQrZQxb06T6JFQaLQxOnYnF5MNfeuDAIHxnljwrlizowAM9S2UI0IrGePfQlLSLWuTxaIMzlWqKxBjCoD_FsNYLWDneTCChNJlrCiw4zOFczQo-Wa8VRw=w1280-h1024-no)

**Comment by RoseCrime** [comment]
Nice work :) 
And here's actions every 300 frames ...:)
`	(frameCount % 300 == 0) ? elements.make() : elements.show();`

I'm using it in my tiny game : 
https://codepen.io/RoseCrime/details/VMzYzj/
And just thought what if I'll actually make game for phones,I'll for sure want to be sure my income will depend from seconds and will not be affected by lags.
