### ISSUE TITLE
2048 (Game)

### ISSUE THREAD

**Issue by sebby13** [CodingTrain/Rainbow-Code#245]
Hello Dan! Can you do an implementation of the 2048 game in P5? 
Also, I would love to see how can you add controls from a touchscreen device.

Here is a link: http://2048game.com/

**Comment by meiamsome** [comment]
Please raise suggestions in Rainbow-Topics. Specifically, 2048 is mentioned here: https://github.com/CodingTrain/Rainbow-Topics/issues/207

Thanks!
