### ISSUE TITLE
Obama Mosaic (p5.js and JS)

### ISSUE THREAD

**Issue by MellyTheFireyMelly** [CodingTrain/Rainbow-Code#246]
You should do the [Obama Mosaic](https://github.com/CodingTrain/Rainbow-Code/tree/master/CodingChallenges/CC_49_ObamaMosaic) that you did but with p5.js and JavaScript!

**Comment by JosefKuchar** [comment]
It's possible, not hard to port, but it will be slow AF, so there is no reason to do this

**Comment by MellyTheFireyMelly** [comment]
Oh okay :(

**Comment by meiamsome** [comment]
Closing in favour of #267, it would be great to have p5 version even though it'd be slow
