### ISSUE TITLE
Lot's of open issues that could be closed.

### ISSUE THREAD

**Issue by Merijn-DH** [CodingTrain/Rainbow-Code#260]
There are a lot of issues still open because the creator didn't close it, even though the problem is already solved or a video request was pointed out to have already been done. There are also a lot of issues that are just very old but never got any comments.. I don't really know what should be done with this.

(P.S. I know it's kind of ironic to make an issue for this..)

**Comment by meiamsome** [comment]
Like that you mean? :D

If you see any more that are closable feel free to leave a final comment and tag me with @ to check it over and close!

**Comment by Merijn-DH** [comment]
Awesome! Much better ;)
