### ISSUE TITLE
 I am not making Money

### ISSUE THREAD

**Issue by Hima1717** [CodingTrain/Rainbow-Code#262]
What should i do ?

**Comment by gvitalie** [comment]
Good morning, Dear @Hima1717 

Look at it and forget. Everything will be [O'Kay](https://en.wikipedia.org/wiki/OK).  

> #### O'Kay is the key symbol and hint to solve the Square the Circle.
> #### Square the Circle is the Famous Ancient Problem that mean: 
>> The Treasure of Treasures, 
>> The Problem of All Answers, 
>> The Key to The Universe, 
>> Everything and Nothing not even Zero, 
>> etc.

_Note: Click on image below will open an YouToBee video_  
[![](https://img.youtube.com/vi/9MQFntVG0tM/maxresdefault.jpg)](https://www.youtube.com/watch?v=9MQFntVG0tM)  

_Note: Click on image below will open an YouToBee video_  
[![](https://img.youtube.com/vi/C4jRsRITPw4/maxresdefault.jpg)](https://www.youtube.com/watch?v=C4jRsRITPw4)

## Directions - Search algorithms

- https://en.wikipedia.org/wiki/Category:Search_algorithms
- https://en.wikipedia.org/wiki/Search_algorithm
- https://en.wikipedia.org/wiki/Category:Internet_search_algorithms
- https://en.wikipedia.org/wiki/List_of_algorithms

**Comment by meiamsome** [comment]
Hello,

I don't think this is the place for this discussion, so I am closing this issue. If you have an issue related to the code in this repository, feel free to raise one.
