### ISSUE TITLE
TRIANGLE_STRIP for p5.js version of perlin noise terrain not working

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Rainbow-Code#27]

**Comment by priestley** [comment]
I have the same issue. Interestingly enough, the code works in the p5 website: http://p5js.org/reference/#/p5/beginShape
When I type it in my local computer, I get the following error: TypeError: this._graphics._getFill is not a function

The code I typed is below:

function setup(){
  createCanvas(100, 100, WEBGL);
}

function draw(){
  background(200);
  beginShape(TRIANGLE_STRIP);
vertex(30, 20);
vertex(85, 20);
vertex(85, 75);
vertex(30, 75);
endShape(CLOSE);
}

**Comment by 5ka1991** [comment]
This is what I made with pure js (without any libraries) inspired by Daniel:

**Comment by jonaaust** [comment]
Any progress on this?

**Comment by bennettscience** [comment]
I got errors when drawing the strip using WebGL. The errors are: `INVALID_VALUE: vertexAttribPointer: index out of range` and ` INVALID_VALUE: enableVertexAttribArray: index out of range`. Not sure how to fix them.

**Comment by axheine** [comment]
I got the same errors than @bennettscience

**Comment by PerryTaga** [comment]
Same errors as @bennettscience as well. Firefox lists:

```
Error: WebGL: enableVertexAttribArray: -1 is not a valid `index`. This value probably comes from a getAttribLocation() call, where this return value -1 means that the passed name didn't correspond to an active attribute in the specified program. 
Error: WebGL: vertexAttribPointer: -1 is not a valid `index`. This value probably comes from a getAttribLocation() call, where this return value -1 means that the passed name didn't correspond to an active attribute in the specified program.
```
Possible issue with beginShape() or vertex()?
With some further testing, I found that the geometry can be drawn with a call to `texture()`.
Create a p5 image object in setup using `img = loadImage("image_path.png)`, then insert `texture(img)` into the draw function. The (triangle_strip) terrain should now render with a blank texture.
Still looking for a way to get the regular mesh working.

**Comment by JakeSchroeder** [comment]
Any progress on this issue?

**Comment by PatrickMurphy** [comment]
This works fine for me in internet explorer,
```
function setup() {
  createCanvas(500, 500, WEBGL);
}

function draw() {
  background(200);
  beginShape(TRIANGLE_STRIP);
  vertex(30, 20, 0);
  vertex(85, 20, 0);
  vertex(85, 75, 0);
  vertex(30, 75, 0);
  endShape(CLOSE);
}

```

I added the 3rd dimension to the coordinates and that made mine render.

Are you sure you just were not seeing the TriangleStrip because it is perpendicular to the camera? I added a rotation animation.

Otherwise try adding `fill(255);` after the `beginShape()` call, it looks like the errors you are experiencing have to do with WebGL trying to place a vertex with a vertex color, but no fill color has been set?

> TypeError: this._graphics._getFill is not a function

It is trying to get the fill color but there is no fill color set?

> Error: WebGL: enableVertexAttribArray: -1 is not a valid `index`. This value probably comes from a getAttribLocation() call, where this return value -1 means that the passed name didn't correspond to an active attribute in the specified program. 
>Error: WebGL: vertexAttribPointer: -1 is not a valid `index`. This value probably comes from a getAttribLocation() call, where this return value -1 means that the passed name didn't correspond to an active attribute in the specified program.

The code[ in the p5.js repo says ](https://github.com/processing/p5.js/blob/4dd42f2136400d33b4eca521b218b07636e16011/src/webgl/p5.RendererGL.Immediate.js#L143)

```
143  shaderProgram.vertexColorAttribute =
144	    gl.getAttribLocation(shaderProgram, 'aVertexColor');
145	  gl.enableVertexAttribArray(shaderProgram.vertexColorAttribute);
```

**Comment by JakeSchroeder** [comment]
I got Dan's port from processing working by adding the fill(255) method call before I draw the vertexes. However, I cant seem to give the triangle strip any stroke color. I want to create the wireframe look, but it doesn't seem to be possible. Here is my code. Take a look...

var cols, rows;
var scl = 20;
var w = 1400;
var h = 1000;

var flying = 0;

var terrain;

function setup() {
  createCanvas(600, 600, WEBGL);
  cols = w / scl;
  rows = h/ scl;

  terrain = [];
  for (var x = 0; x < cols; x++) {
    terrain[x] = [];
  }
}

function draw() {

  flying -= 0.1;
  var yoff = flying;
  for (var y = 0; y < rows; y++) {
    var xoff = 0;
    for (var x = 0; x < cols; x++) {
      terrain[x][y] = map(noise(xoff, yoff), 0, 1, -100, 100);
      xoff += 0.2;
    }
    yoff += 0.2;
  }


  background(50);
  translate(0, 50);
  rotateX(-PI/3);
  translate(-w/2, -h/2);

  for (var y = 0; y < rows-1; y++) {
    beginShape(TRIANGLE_STRIP);
    fill(0);
    stroke(255); //this stroke does not get applied. However, it seems to work when I add it to p5.js's triangle strip example.
    strokeWeight(1);
    for (var x = 0; x < cols; x++) {

      push(); //if I remove this, the entire render breaks and nothing shows up, although I don't get any error.

      translate(x*scl, y*scl, terrain[x][y]);
      vertex(x*scl, y*scl, terrain[x][y]);
      vertex(x*scl, (y+1)*scl, terrain[x][y+1]);
      pop();


    }
    endShape();

  }

}

**Comment by eivindml** [comment]
Anyone have any luck with this yet? It seems like it's not possible to have `TRIANGLE_STRIP` with `noFill()` and `stroke()`, when you have three coordinates.

**Comment by Quentin-Guille** [comment]
so far i've done this using the code:

`    // Daniel Shiffman
    // http://codingrainbow.com
    // http://patreon.com/codingrainbow
    // Code for: https://youtu.be/IKB1hWWedMk

    var cols, rows;
    var scl = 20;
    var w = 500;
    var h = 500;

    var flying = 0;

    var terrain;

    function setup() {
      createCanvas(500, 500, WEBGL);
      cols = w / scl;
      rows = h/ scl;

      terrain = [];
      for (var x = 0; x < cols; x++) {
        terrain[x] = [];
      }
    }

    function draw() {

      flying -= 0.1;
      var yoff = flying;
      for (var y = 0; y < rows; y++) {
        var xoff = 0;
        for (var x = 0; x < cols; x++) {
          terrain[x][y] = map(noise(xoff, yoff), 0, 1, -100, 100);
          xoff += 0.2;
        }
        yoff += 0.2;
      }


      background(50);
      translate(0, 50);
      rotateX(-PI/3);
      translate(-w*.75, -h/2);

      for (var y = 0; y < rows-1; y++) {

        beginShape(LINES);
        fill(255);
        stroke(0);
        for (var x = 0; x < cols; x++) {

          push();
          translate(x*scl, y*scl, terrain[x][y]);
          vertex(x*scl, y*scl, terrain[x][y]);
          vertex(x*scl, (y+1)*scl, terrain[x][y+1]);
          if(x>0) {
          vertex(x*scl, y*scl, terrain[x][y]);
          vertex((x-1)*scl, y*scl, terrain[x-1][y]);
          }
          pop();


        }
        endShape();

      }

    }

    function windowResized() {
      resizeCanvas(windowWidth, windowHeight);
    }`

**Comment by meiamsome** [comment]
This has been fixed

**Comment by eivindml** [comment]
Has anyone actually got this working? Seems to me like there is still bugs.

See this: https://github.com/processing/p5.js/issues/2344
