### ISSUE TITLE
Video & Code for 10.6 Painting with p5js don't match

### ISSUE THREAD

**Issue by haideralipunjabi** [CodingTrain/Rainbow-Code#271]
I was searching for the code for [10.6 Painting with Pixels - p5js Tutorial](https://www.youtube.com/watch?v=0V3uYA1hafk), and the description linked to [here](https://github.com/CodingTrain/Rainbow-Code/tree/master/Tutorials/P5JS/p5.js_video/10.6_p5.js_painting). But the code doesn't match

**Comment by Merijn-DH** [comment]
Try this https://github.com/CodingTrain/Rainbow-Code/tree/master/Tutorials/P5JS/p5.js_video/11.6_p5.js_painting

It's actually 11.6, not 10.6

**Comment by meiamsome** [comment]
Yes, things are being renumbered a bit at the moment - sorry for the confusion!

**Comment by Merijn-DH** [comment]
can this issue be closed?

**Comment by meiamsome** [comment]
I was waiting for the video's description to be fixed, as it now is. Thanks for pinging me, @Merijn-DH
