### ISSUE TITLE
p5.Speech error : Uncaught TypeError: p5.SpeechRec is not a constructor

### ISSUE THREAD

**Issue by ranveerpunia** [CodingTrain/Rainbow-Code#292]
while trying to run code copied from your github page for text to speech tutorial getting this error in console:
__________________________________________________________________________________
sketch.js:50 Uncaught TypeError: p5.SpeechRec is not a constructor
    at setup (sketch.js:50)
    at e.<anonymous> (p5.min.js:31)
    at e.<anonymous> (p5.min.js:31)
    at new e (p5.min.js:31)
    at e (p5.min.js:31)
.___________________________________________________________
however example code im getting from ability project website  which is in html form is running properly.
i have added p5.speech file in index.html also

**Comment by meiamsome** [comment]
Which code in particular where you looking at?

**Comment by ranveerpunia** [comment]
solved had to move p5.speech.js file to same folder as sketch.js .thanks meiamsome

**Comment by gaba5** [comment]
Getting the same issue? p5.speech is in the same folder as sketch and its linked in HTML
