### ISSUE TITLE
Missing Tutorial Code

### ISSUE THREAD

**Issue by meiamsome** [CodingTrain/Rainbow-Code#293]
The following p5.js tutorials are all missing code in the repository. If anyone would like to PR exact transcripts of the code in those videos, that'd be great.

- [x] 9.1 - Transformations
- [x] 9.2 - Transformations
- [x] 9.3 - Transformations
- [ ] 9.14 - Loading Animation
- [x] 9.15 - 2D arrays
- [x] 9.17 - arguments
- [x] 9.19 - Prototypes
- [x] 9.20 - Polar Coords

- [ ] 10.04 - Loading JSON data from  a URL (api.open-notify.org)
- [ ] 10.05 - Working with APIs in Javascript (api.openweathermap.org)
- [ ] 10.07 - API Query with Javascript setInterval (api.open-notify.org)
- [ ] 10.08 - Wordnik API and Javascript
- [ ] 10.09 - New York Times API

**Comment by Merijn-DH** [comment]
Do you want 3 different folders for 9.1, 9.2 and 9.3 or just the end result of 9.3 in a folder '9.1-9.3'?

**Comment by meiamsome** [comment]
@Merijn-DH Three different folders! Seperated them out to represent that now! Cheers!

**Comment by Merijn-DH** [comment]
@shiffman for '9.14: Loading Animation' the file 'rainbow.mp3' is used. Can I find that file somewhere or can you send it to me so I can include it?

**Comment by shiffman** [comment]
Sorry for very late reply, catching up on these issues. . @Merijn-DH I actually can't seem to find this file on my computer but you can just use anything from the sound tutorials? The point is just demonstrating something that takes a while to load.

**Comment by Merijn-DH** [comment]
@shiffman will do!
