### ISSUE TITLE
Can We Add Text input or Text Area in processing and A Icon Image Too Can We Can????

### ISSUE THREAD

**Issue by omkardikshit** [CodingTrain/Rainbow-Code#306]
<h1>Can We Add Text input or Text Area in processing and A Icon Image Too Can We Can????</h1>

**Comment by Merijn-DH** [comment]
Processing natively doesn't have any GUI elements, but there are some libraries that can add these. For instance check out controlP5: http://www.sojamo.de/libraries/controlP5/

**Comment by shiffman** [comment]
Programming questions should be asked at forum.processing.org, thanks!
