### ISSUE TITLE
Idea for a video

### ISSUE THREAD

**Issue by lukas2005** [CodingTrain/Rainbow-Code#324]
Make a generator of cool polygon seamless loops like this one: https://www.shutterstock.com/pl/video/clip-10536290-stock-footage-smooth-polygons-waves-perfect-seamless-loop-of-slowmotion-polygon-waves-background-animation-k.html

**Comment by jamet-julien** [comment]
You can look this video ( it's the same thing ) : https://www.youtube.com/watch?v=ELpZW62HGVs&list=PLRqwX-V7Uu6bgPNQAdxQZpJuJCjeOr7VD&index=7

**Comment by zhansayasartbay** [comment]
hello, I have Splat project ,which consisis of 4 phases (lexer,parser..)to
do in Java , deadline 18.12..
Do u know any tutorials or helpful codes , at which I can loook...

**Comment by zhansayasartbay** [comment]
I'm beginner in Java, I need help

**Comment by lukas2005** [comment]
not really on the video that i linked the camera is (or atleast looks) stationary also its looping seamlessly meaning that it can be used as a background (instead of looping seamlessly u can also just make it have 2 modes 1 seamless video 2 infinite continuous generation/changing) also it would be better if instead of generating something new continuosly just moving around the old points

**Comment by lukas2005** [comment]
@zhansayasartbay ???

**Comment by zhansayasartbay** [comment]
sorry) just ignore

**Comment by shiffman** [comment]
Suggestions for videos go here: https://github.com/CodingTrain/Rainbow-Topics/issues
