### ISSUE TITLE
Chrome extension github pages offline

### ISSUE THREAD

**Issue by BLCKPSTV** [CodingTrain/Rainbow-Code#330]
Hi,

The chrome extensions p5js pages (word, sketch, kittension) are offline?

**Comment by Merijn-DH** [comment]
Chrome extensions do not have an index.html, this is why the 'Example Running Online' is kind of useless in this case. I guess the README was just copied from other coding challenges.

To use the extensions you should download the folder and add it to chrome://extensions. (make sure you have development mode enabled.)

**Comment by meiamsome** [comment]
Thanks for the report, removed the misleading links!
