### ISSUE TITLE
webgl vertex

### ISSUE THREAD

**Issue by realcygnus** [CodingTrain/Rainbow-Code#336]
win 7 chrome 
latest p5 libs

beginShape/vertex/endshape dosent work at all with webgl !

68723: Uncaught TypeError: Cannot read property 'location' of undefined

**Comment by shiffman** [comment]
Thanks for the report! Bug reports for p5 should go here: https://github.com/processing/p5.js/issues

I would include the sketch test code you are trying, as well as the p5.js version number!
