### ISSUE TITLE
loadImage / createImage issue? 

### ISSUE THREAD

**Issue by BLCKPSTV** [CodingTrain/Rainbow-Code#337]
Hi, 

I'm trying to get a sketch to work, I already asked on the processing forum if my sketch is wrong? 
I looked up all I can from p5js image functions. 

In the example I was following I needed to do loadImg(), but after trying something out with a Gif I learned that when I write the code the createImg() only works. Well let's say partly in my sketch. 

The code is running on a npm http-server like suggested. 
My html is referring to all the correct scripts. 

my sketch looks like this. 
```

let faces = [];
let idx = 0;
 
const INTER = 10 * 1000;
 
function preload(){
  for (let i = 0; i < 4; i++) {
    faces[i] = createImg('images/' + i + '.png');
  }
}
 
function setup() {
    createCanvas(800, 900);
    setInterval(() => idx = (idx + 1) % faces.length, INTER);
}
 
function draw() {
  image(faces[idx], 0, 0);
}
```

In my case it shows me all the images first in my browser. And then a last "holder" where the images run after each other like the script tells. 
When using loadImg() in the preload function, I get a black screen. 

Can anybody replicate this? And or maybe tell me what I'm doing wrong and if this a p5js issue? 
Thanks!

**Comment by spiray** [comment]
What happens when you log `faces` to the console? It definitely looks like you should be using ```loadImage()``` the way you are writing your sketch. ```createImage()``` is more for working with pixels. Read more @ https://p5js.org/reference/#/p5/loadImage.

**Comment by BLCKPSTV** [comment]
console.log(faces) in preload gives me with createImg()
```

[p5.Element]0: p5.Element {elt: img, _pInst: undefined, _events: {…}, width: 808, height: 808, …}1: p5.Element {elt: img, _pInst: undefined, _events: {…}, width: 768, height: 768, …}2: p5.Element {elt: img, _pInst: undefined, _events: {…}, width: 2400, height: 2880, …}3: p5.Element {elt: img, _pInst: undefined, _events: {…}, width: 1448, height: 1448, …}length: 4__proto__: Array(0)
sketch.js:9 (2) [p5.Element, p5.Element]0: p5.Element {elt: img, _pInst: undefined, _events: {…}, width: 808, height: 808, …}1: p5.Element {elt: img, _pInst: undefined, _events: {…}, width: 768, height: 768, …}2: p5.Element {elt: img, _pInst: undefined, _events: {…}, width: 2400, height: 2880, …}3: p5.Element {elt: img, _pInst: undefined, _events: {…}, width: 1448, height: 1448, …}length: 4__proto__: Array(0)
sketch.js:9 (3) [p5.Element, p5.Element, p5.Element]0: p5.Element {elt: img, _pInst: undefined, _events: {…}, width: 808, height: 808, …}1: p5.Element {elt: img, _pInst: undefined, _events: {…}, width: 768, height: 768, …}2: p5.Element {elt: img, _pInst: undefined, _events: {…}, width: 2400, height: 2880, …}3: p5.Element {elt: img, _pInst: undefined, _events: {…}, width: 1448, height: 1448, …}length: 4__proto__: Array(0)
sketch.js:9 (4) [p5.Element, p5.Element, p5.Element, p5.Element]0: p5.Element {elt: img, _pInst: undefined, _events: {…}, width: 808, height: 808, …}1: p5.Element {elt: img, _pInst: undefined, _events: {…}, width: 768, height: 768, …}2: p5.Element {elt: img, _pInst: undefined, _events: {…}, width: 2400, height: 2880, …}3: p5.Element {elt: img, _pInst: undefined, _events: {…}, width: 1448, height: 1448, …}length: 4__proto__: Array(0)concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toString: ƒ toString()unshift: ƒ unshift()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}__proto__: Object
```

**Comment by spiray** [comment]
Use ```loadImage()```, ```createImage()``` is used very differently.

**Comment by Merijn-DH** [comment]
`createImg()` and `createImage()` are two very different things in p5. One is part of the DOM library to create an `<img>` object in the html page while the other creates one in the canvas. As @spiray already pointed out, in your case you want to use `loadImage()' (not `loadImg()`). Please read the p5 documentation on it [here](https://p5js.org/reference/#/p5/loadImage), it gives a useful example.

**Comment by spiray** [comment]
@Merijn-DH Thanks for clarifying that. @BLCKPSTV please let me know if you are still having challenges with this.

**Comment by shiffman** [comment]
I should definitely do a video about `createImg()` vs `createImage()` and `loadImage()`.
