### ISSUE TITLE
WebGL console errors when running my p5js sketches

### ISSUE THREAD

**Issue by SetupandDraw** [CodingTrain/Rainbow-Code#343]
getting multiple errors form the console when testing my sketch on Chrome 62.0.3202.94, running on Mac Os 10.11.6﻿
".Offscreen-For-WebGL-0x7f8a62017e00]RENDER WARNING: there is no texture bound to the unit 0 error"
I am running the aame exact code seen in "18.3: Light and Material" tutorial.

**Comment by Merijn-DH** [comment]
The code works fine for me. Can you paste your code in here and maybe add a screenshot of chrome with the error message?

**Comment by SetupandDraw** [comment]
Sure, here is the code
`let angle = 0;

function setup() {
  createCanvas(400, 300, WEBGL);
}

function draw() {
  let dx = mouseX - width / 2;
  let dy = mouseY - height / 2;
  let v = createVector(dx, dy, 0);
  //v.normalize();
  v.div(100);

  ambientLight(0, 0, 255);
  directionalLight(255, 0, 0, v);
  //pointLight(255, 0, 0, 200, 0, 0);

  background(175);

  rotateX(angle);
  rotateY(angle * 0.3);
  rotateZ(angle * 1.2);

  //noStroke();
  stroke(0);
  ambientMaterial(255);
  //specularMaterial(255);
  //fill(0, 0, 255);
  torus(100, 25);

  angle += 0.03;
}`

and here is the screenshot with the errors: 
<img width="801" alt="screenshot 2017-12-29 16 15 47" src="https://user-images.githubusercontent.com/13521729/34440199-c5b0a01e-ecb3-11e7-8eef-7fbdfdb8eea7.png">

**Comment by Merijn-DH** [comment]
Thanks for the extra information, I was able to reproduce the problem. However since it is a warning, I normally say "If it works, just ignore it". This is an issue on the p5.js end, not on yours. Maybe newer versions of p5.js will fix this.

**Comment by SetupandDraw** [comment]
Thank you Marijn, yes, the sketch indeed works without any problems, anyway I was pointing it out so, people working on P5Js know it's there.

**Comment by Merijn-DH** [comment]
If you think this is an issue worth notifying the developers, you can file it on https://github.com/processing/p5.js :)
