### ISSUE TITLE
I can't open p5.js file

### ISSUE THREAD

**Issue by EuGenius23** [CodingTrain/Rainbow-Code#344]
When I download it and export the files from the .zip downloaded, the computer comes with an alert message that says there is a syntax error or something. I don't know what is the problem. I just wanted to start learning programming with p5.js.
I don't know if I didn't open the files correctly or if I downloaded them wrong or something.
Anyway, thanks for the attention.

**Comment by spiray** [comment]
Hi, Can you provide a screenshot so i can help you out better?

**Comment by shiffman** [comment]
Best to ask at forum.processing.org in the p5.js category! You might check out my "workflow" videos for help too.

https://www.youtube.com/watch?v=HZ4D3wDRaec
