### ISSUE TITLE
Menu links don’t hide on mobile

### ISSUE THREAD

**Issue by nilsweb** [CodingTrain/Rainbow-Code#370]
Just so I don’t forget (or if somebody finds the issue straight away):

I’ve just noticed that the links in the top navigation bar don’t hide on mobile devices. They are just hovering over the page content even though they should only be clickable when the menu is extended.

I definitely thought that this worked before but I don’t think anything changed in the code since then... Maybe I haven’t noticed?

**Comment by shiffman** [comment]
Could it be when I removed the header image? https://github.com/CodingTrain/Rainbow-Code/commit/0fe45d83dab9071fb0646f57f92752ad4915be94

**Comment by nilsweb** [comment]
Hmm... You just commented out the image tag... That shouldn’t break it but I haven’t had the time to look into this more deeply. Will definitely happen over the weekend.

**Comment by Link2Twenty** [comment]
Works fine for me (google pixel), the sass looks fine too.

**Comment by Maik1999** [comment]
I added a visibility:hidden to the links for mobile and if the checkbox is checked I set them to visible.
But I am not able to get it in sass and test it right now.
