### ISSUE TITLE
New issue label

### ISSUE THREAD

**Issue by Link2Twenty** [CodingTrain/Rainbow-Code#375]
Can you add a new label, maybe called `website`, that you can add to all website related issues. It would make it a lot easier for people to see where they can help 🙂

Here's the documentation in case you don't know how to do it
[https://help.github.com/articles/creating-a-label/](https://help.github.com/articles/creating-a-label/)

**Comment by shiffman** [comment]
working on this now!

**Comment by nilsweb** [comment]
Good point! There should also be a milestone related to finishing the website (or rather bringing it to an up-to-date state).

**Comment by shiffman** [comment]
See: https://github.com/CodingTrain/Rainbow-Code/issues?q=is%3Aissue+is%3Aopen+label%3Awebsite Let me know if I missed any!

**Comment by shiffman** [comment]
@nilsweb I'm not as experienced with milestones, do you want to set one up?

**Comment by nilsweb** [comment]
I already did this morning. Check it out [here](https://github.com/CodingTrain/Rainbow-Code/milestone/1).
