### ISSUE TITLE
Dithering challenge 90 page

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Rainbow-Code#383]
I added the code for the dithering challenge: 05c1f55a064ddd6f2551cefbe172d8812219b9df

If anyone wants to take a crack at the MD file, here's the youtube link!

https://www.youtube.com/watch?v=0L2n8Tg2FwI

Releasing video tomorrow!

**Comment by nilsweb** [comment]
Fixed by @blinkityblank with commit b2f1a7b19b5d1c34734e233bc63a1ede2709a875
