### ISSUE TITLE
star field doesn't work with WEBGL in p5js

### ISSUE THREAD

**Issue by softpunch** [CodingTrain/Rainbow-Code#41]
Hi!

I was toying with the star field example here, 
and I wanted to add some planets, etc., so I turned on WEBGL.

However, as soon as I enable WEBGL,
the stars disappear, and I get:
**"7790: Uncaught TypeError: undefined is not a function"**

I tried turning a few things on and off to fix it, but no luck.

I'm using 0.6.1 on a MacBook with El Capitan (and I'm using the p5.js editor).

[Not sure if I should be posting this here or on the p5 page, 
apologies if I chose the wrong one!]

**Comment by softpunch** [comment]
To be clear, 
I did adjust the shapes to exist in a 3D plane.
I also tried swapping out the p5.js Star constructor with a version based on NOC Cosmos, 
among other things.
```

var stars = [];
var speed;
var depth;
var factor;

function setup() {
  createCanvas(600, 600, WEBGL);
  depth = 5000;
  factor = 1;
  speed = 5;
  
  for (var i = 0; i < 800; i++) {
    stars[i] = new Star();
  }
}

function draw() {
  background(0);
  ambientLight(255);
  for (var i = 0; i < stars.length; i++) {
    stars[i].update();
    stars[i].show();
  }
}

var pos;
var originalVel;
var vel;

function Star() {
  pos = createVector(random(-5*width, 5*width), random(-5*height, 5*height), random(-depth, depth));
  originalVel = createVector(0, 0, random(1, 5));
  vel = copy(originalVel, vel);

  this.update = function() {
    vel.z = originalVel.z*factor;  
    pos.add(vel);
    // Recycle the star when it passes far away
    if (pos.z > depth)
      pos.z = -depth;
    }
  }

  this.show = function() {
    stroke(255, 127);
    strokeWeight(2.5);
    point(pos.x, pos.y, pos.z);
    beginShape();
    for (var i = 0; i < 5; i++) {
      vertex(pos.x-vel.x*i, pos.y-vel.y*i, pos.z-vel.z*i);
    }
    endShape();
  }
```

**Comment by shiffman** [comment]
This should be attempted again now that I've done the WebGL tutorials!
