### ISSUE TITLE
Numbering of the videos on the website positioning 

### ISSUE THREAD

**Issue by blinkityblank** [CodingTrain/Rainbow-Code#411]
I noticed that the numbering of each video on the website comes in conflict with the thumbnails of the videos. It's often covering part of the title of the video in the upper left corner.

![image](https://user-images.githubusercontent.com/6036839/35523091-012c3d56-04ec-11e8-8a00-a6c179365534.png)

Maybe the numbering could be positioned in the lower right corner of the thumbnail, as there is nothing to cover in that corner.

**Comment by nilsweb** [comment]
Thanks to @TurqDevDesign, this was fixed with #423!
