### ISSUE TITLE
unlisted challenge shows up as most recent

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Rainbow-Code#440]
I don't really mind this but I suppose there could be a scenario where it's a problem but on the homepage an unlisted video challenge will show up.  You can see right now as the "Double Pendulum" video is unlisted on YouTube, but appears on the site.

**Comment by blinkityblank** [comment]
I put in the wrong date, so it shows up already. I meant to put tomorrow's date, so that it only shows up tomorrow.
But I guess that the easiest way to remedy this is to only add the .md file after the video has been published?

**Comment by blinkityblank** [comment]
I fixed this instance of the problem by fixing the dates in the .md files, so the double pendulum video will only show up tomorrow.
But it will show up at midnight I'm guessing, so still before the video was made public...

**Comment by shiffman** [comment]
oh i see. . in this case it's fine! When the video is ready I'm very happy for people to find it and watch it so it's not a big deal if every once in a while it shows up on the site early too. For your workflow I think it's easier for you to add the md files when you are working on the videos so let's no worry too much. Now that I know I can always change the date on the website too etc.
