### ISSUE TITLE
69.4 contributions not showing correctly

### ISSUE THREAD

**Issue by Jamesinvi** [CodingTrain/Rainbow-Code#443]
i added my contribution to the 69.4 coding challenge and it was showing correctly but it seems this is no longer the case

**Comment by shiffman** [comment]
More of a reason for #417! (I keep merging things that break the site.) I believe I fixed it with https://github.com/CodingTrain/Rainbow-Code/commit/0eb329fa64073d2134070f0121cfba328b8840ea. If you see it please close the issue!

**Comment by Jamesinvi** [comment]
now showing correctly! closing the issue
