### ISSUE TITLE
Help Porting to Lua

### ISSUE THREAD

**Issue by flamendless** [CodingTrain/Rainbow-Code#46]
I need help in porting this code for learning in lua. Using the Love2D framework, up until the checkNeighbors function work, although instead of checking and highlighting random tiles next to the current one, the next cell is sometimes diagonal and very random. Here is the repo. Thanks

[maze.zip](https://github.com/CodingRainbow/Rainbow-Code/files/628804/maze.zip)

**Comment by DonRyuDragoni** [comment]
Hey, if you still need help, I ported the maze generator (I guess that's what you're working on? can't open the zip file here) [to Lua+Löve2D](https://github.com/DonRyuDragoni/MazeGen). I do not promise the code is clean or well-designed, though.

**Comment by flamendless** [comment]
Thank you. Ive got stucked so I switched to a new project. Thanks
