### ISSUE TITLE
P5.js vs Processing.js

### ISSUE THREAD

**Issue by ChristosSoteriou** [CodingTrain/Rainbow-Code#60]
Hello,

I would like to know what are the differences between P5.js and Processing.js

Thank you...

**Comment by SovietKetchup** [comment]
Processing applications are created using a coding syntax.and format based on the programming language Java. If you have experience with Java that would be the recommended option.

p5.js is an adaptation of Processing for JavaScript, a used in the browser.

There are other languages you can use to make Processing like applications such as Python, and more, along with unnoficial adaptions such as propane for Ruby.

For learning I would reccomend p5.js, but it does t matter much as both are available in the processing program.
