### ISSUE TITLE
Virtual Oscilloscope visualizer for sound in p5.js

### ISSUE THREAD

**Issue by Velkas** [CodingTrain/Rainbow-Code#61]
I have an old oscilloscope that has a way to configure it for audio frequency measurement. There are some cool things you can do with drawing images using sound, but the scope I have is broken. It would be cool as a learning exercise to recreate how the oscilloscope draws to a screen in p5.js which can take a sound signal (so a more advanced version of your sound in p5.js series). I just don't know how to convert how the oscilloscope works into code.

**Comment by meiamsome** [comment]
Hello, this repository is for the code from tutorials only, please but all topic suggestions/requests in https://github.com/CodingTrain/Rainbow-Topics thanks.
