### ISSUE TITLE
Please help me map the time to the arcs angle

### ISSUE THREAD

**Issue by DknPry** [CodingTrain/Rainbow-Code#65]
```javascript
function updateTimer(deadline){
  var time = deadline - new Date();
  return {
    'minutes': Math.floor( (time/1000/60) % 60 ),
    'seconds': Math.floor( (time/1000) % 60 ),
    'total' : time
  };
}

var o = 350;


function setup() {
 createCanvas (850,400);
  
}

function draw() {
  background (200,200,200,0);

  r = map (mouseX,0.00009,850,0.0,TWO_PI)
  
  
  //ellipse
  fill (250, 200, 200);
  ellipse (width/2,height/2,o,o);
  
  

  push();
  translate(425,200);
  rotate(4.712);
  fill(255,100,50);
  arc(0,0,o,o,0.0,r); 
  pop();
 
  

}


function animateClock(span){
  span.className = "turn";
  setTimeout(function(){
    span.className = "";
  },700);
}

function startTimer(id, deadline){
  var timerInterval = setInterval(function(){
    var clock = document.getElementById(id);
    var timer = updateTimer(deadline);

    clock.innerHTML = '<span>' + timer.minutes + '</span>' + '<span>' + timer.seconds + '</span>';

    //animations
    var spans = clock.getElementsByTagName("span");
    animateClock(spans[3]);
    if(timer.seconds == 59) animateClock(spans[2]);
    if(timer.minutes == 59 && timer.seconds == 59) animateClock(spans[1]);

    //check for end of timer
    if(timer.total < 1){
      clearInterval(timerInterval);
      clock.innerHTML = '<span>0</span><span>0</span>';
    }


  }, 1000);
}


window.onload = function(){
  var deadline = new Date("1/1/20 3:01:00");
  startTimer("clock", deadline);
};
```

**Comment by pranavgade20** [comment]
Use millis():
You WILL need p5.js library for this

`function updateTimer(deadline){
var time = deadline - new Date();
return {
'minutes': Math.floor( (time/1000/60) % 60 ),
'seconds': Math.floor( (time/1000) % 60 ),
'total' : time
};
}

var o = 350;

function setup() {
createCanvas (850,400);

}

function draw() {
background (200,200,200,0);

r = map (((millis()/1)%1000),0,1000,0.0,TWO_PI)//replace "millis()/1" with "millis()/60" to make it a minute timer

//ellipse
fill (250, 200, 200);
ellipse (width/2,height/2,o,o);

push();
translate(425,200);
rotate(4.712);
fill(255,100,50);
arc(0,0,o,o,0.0,r);
pop();

}

function animateClock(span){
span.className = "turn";
setTimeout(function(){
span.className = "";
},700);
}

function startTimer(id, deadline){
var timerInterval = setInterval(function(){
var clock = document.getElementById(id);
var timer = updateTimer(deadline);

clock.innerHTML = '<span>' + timer.minutes + '</span>' + '<span>' + timer.seconds + '</span>';

//animations
var spans = clock.getElementsByTagName("span");
animateClock(spans[3]);
if(timer.seconds == 59) animateClock(spans[2]);
if(timer.minutes == 59 && timer.seconds == 59) animateClock(spans[1]);

//check for end of timer
if(timer.total < 1){
  clearInterval(timerInterval);
  clock.innerHTML = '<span>0</span><span>0</span>';
}

}, 1000);
}

window.onload = function(){
var deadline = new Date("1/1/20 3:01:00");
startTimer("clock", deadline);
}`

**Comment by meiamsome** [comment]
I'm assuming that @pranavgade20's comment was helpful and closing this as resolved!
