### ISSUE TITLE
Suggestion: Follow up on the supershape videos, A "4-Dimentional Space"

### ISSUE THREAD

**Issue by xmicks** [CodingTrain/Rainbow-Code#68]
You should do a follow up video on the supershape video series with the "4D Space"

See the animated gif on this wikipedia page: https://en.wikipedia.org/wiki/Four-dimensional_space 
Also formulas on the shape are mentioned on the page.
And also see: https://en.wikipedia.org/wiki/Tesseract

**Comment by meiamsome** [comment]
Hello, this repository is for the code from tutorials only, please but all topic suggestions/requests in https://github.com/CodingTrain/Rainbow-Topics thanks.
