### ISSUE TITLE
Problem with some of the folder names in Rainbow-Code/p5.js/ The repository becomes undeletable on windows!

### ISSUE THREAD

**Issue by piemo** [CodingTrain/Rainbow-Code#78]
as title says...some folders in that path ends with a space, and windows is unable to delete them. The only way to delete them was to manually do a painstaking process in cmd.

PLEASE SOMEONE FIX THIS ASAP

**Comment by JosefKuchar** [comment]
I'm trying to fix it, i can't clone repo to windows, because whitespace at the and

**Comment by shiffman** [comment]
I can take a look at this now. . one moment. . .

**Comment by JosefKuchar** [comment]
I tried to rename folders and push to my repo, but whitespace %20 is still there. Maybe we must delete folders and create new ones with same files

**Comment by shiffman** [comment]
Did I get them all or are there still some? It's hard to see which ones have spaces so feel free to add a list to this thread.

**Comment by JosefKuchar** [comment]
2.3_0_p5.js_JavaScript_without_objects
2.3_1_p5.js_JavaScript_with_objects
3.1_p5.js_Introduction_to_Conditional_Statements
3.2_p5.js_The_Bouncing_Ball
3.3_p5.js_Else_and_ElseIf_and_and_or
3.4_1_p5.js_Boolean_variables
3.4_p5.js_Boolean_variables
4.2a_Nested_loops
4.2b_Nested_loops
5.2_p5.js_Function_parameters_and_arguments
5.3_p5.js_Functions_and_return
7.2_p5.js_Creating_HTML_elements_with_JavaScript
7.4_p5.js_Handling_DOM_events_with_callbacks
7.5_p5.js_Other_events_and_inputs
7.8_p5.js_CSS_Selectors
7.9_p5.js_select_selectAll_with_CSS_selectors

**Comment by shiffman** [comment]
Ok, should be good now! Let me know and I'll close.

**Comment by JosefKuchar** [comment]
It's OK now, thank you :)
